### ISSUE TITLE
[v3-pro] c-show and c-active not set for extended path

### ISSUE THREAD

**Issue by wittfabian** [coreui/coreui#146]
**c-show and c-active are not automatically set if the path does not match 100%**

c-show and c-active are added: /account/
c-show and c-active are **not** added: /account/password/

```
<li class="c-sidebar-nav-dropdown">
    <a class="c-sidebar-nav-dropdown-toggle" href="#">
        <i class="far fa-user c-sidebar-nav-icon"></i>
        Account
    </a>

    <ul class="c-sidebar-nav-dropdown-items">
        <li class="c-sidebar-nav-item">
            <a class="c-sidebar-nav-link" href="/account/">
                Profile
            </a>
        </li>
    </ul>
</li>
```

- Operating system and version: macOS 10.15.6
- Browser and version: Firefox 79.0 (64-Bit)

**Comment by mrholek** [comment]
Fixed in v3.3.0

**Comment by wittfabian** [comment]
Nothing changed in https://www.npmjs.com/package/@coreui/coreui-pro v3.3.0.
Problem is still there.

**Comment by wittfabian** [comment]
@mrholek Still not working! Where can I find the change?

**Comment by wittfabian** [comment]
v3.4.0: Still not working!

**Comment by wittfabian** [comment]
@mrholek Please reopen the issue!

**Comment by wittfabian** [comment]
I changed:
- `Default$b.activeLinksExact` to false (line 9528, coreui.bundle.js)
- `element.href.startsWith(currentUrl)` to `currentUrl.startsWith(element.href)` (line 9956, coreui.bundle.js)

**Comment by wittfabian** [comment]
Same for v4.1-pro

**Comment by ps613** [comment]
@mrholek  I still have this issue with CoreUI Pro 5.9.0

**Comment by mrholek** [comment]
@ps613 this feature is available, but we don't have it documented. You can add `data-coreui-active-links-exact="false"` to `<ul class="sidebar-nav" data-coreui-active-links-exact="false">...</ul>`
