### ISSUE TITLE
[PRO] - Dark mode not rendering properly

### ISSUE THREAD

**Issue by abunch** [coreui/coreui#382]
Before opening:

- [Search for duplicate or closed issues](https://github.com/coreui/coreui/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/coreui/coreui/blob/main/.github/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version: Mac
- Browser and version: Chrome, Brave, Safari, Firefox

Steps to repro:

- yarn build
- yarn serve
- switch to dark mode
- click any icon on the header toolbar and observe the problem

This issue does not appear in the demo site: https://coreui.io/demo/4.2/dark/
**It is present in the pro version.**

<img width="275" alt="Screen Shot 2022-03-20 at 5 18 14 PM" src="https://user-images.githubusercontent.com/2077840/159188473-e913c6bb-b977-4cd1-b186-2c237f873e16.png">
<img width="369" alt="Screen Shot 2022-03-20 at 5 20 12 PM" src="https://user-images.githubusercontent.com/2077840/159188476-4d44bd85-5735-4d54-9662-78b4843f3567.png">
<img width="769" alt="Screen Shot 2022-03-20 at 5 20 16 PM" src="https://user-images.githubusercontent.com/2077840/159188479-2bfae36b-903d-4907-928c-83e1557c0fb5.png">
<img width="388" alt="Screen Shot 2022-03-20 at 5 20 20 PM" src="https://user-images.githubusercontent.com/2077840/159188483-19548bae-3c0e-453b-8d78-3ecedbefdccb.png">

**Comment by xidedix** [comment]
Hello @abunch - thanks for pointing this out. 
Some css classes are missing on dark demo templates. 
We'll look at this.

**Comment by mrholek** [comment]
@abunch fixed in v4.1.1, you can download the latest version here - https://coreui.io/download/

**Comment by abunch** [comment]
@mrholek I downloaded 4.1.1 from that very link just yesterday at about 4:30pm local time and it was not fixed.

<img width="738" alt="Screen Shot 2022-03-21 at 6 28 58 PM" src="https://user-images.githubusercontent.com/2077840/159379417-0fb5422f-02cd-4e5d-a537-04b007858450.png">
.

**Comment by mrholek** [comment]
@abunch Can you paste the content of your package.json file?

**Comment by abunch** [comment]
```
{
  "name": "@coreui/coreui-pro-bootstrap-admin-template",
  "version": "4.1.1",
  "description": "Bootstrap Admin Template",
  "keywords": [
    "admin",
    "admin panel",
    "admin template",
    "bootstrap",
    "css",
    "dashboard",
    "framework",
    "front-end",
    "responsive",
    "sass",
    "ui kit",
    "webapp"
  ],
  "homepage": "https://coreui.io",
  "bugs": {
    "url": "https://github.com/coreui/coreui-pro-bootstrap-admin-template/issues",
    "email": "support@coreui.io"
  },
  "license": "MIT",
  "author": {
    "name": "creativeLabs Łukasz Holeczek",
    "url": "https://coreui.io",
    "github": "https://github.com/coreui",
    "twitter": "https://twitter.com/core_ui"
  },
  "contributors": [
    {
      "name": "CoreUI Core Team",
      "url": "https://github.com/orgs/coreui/people"
    }
  ],
  "main": "dist/index.html",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/coreui/coreui-pro-bootstrap-admin-template.git"
  },
  "scripts": {
    "build": "npm run build-from-html",
    "build-vendors": "node build/vendors.js",
    "build-from-html": "npm-run-all clean --parallel css js copy --sequential build-vendors",
    "build-from-pug": "npm-run-all clean --parallel css js copy-assets pug-dist --sequential build-vendors",
    "clean": "rimraf dist",
    "copy": "npm-run-all --parallel copy-*",
    "copy-assets": "copyfiles -a -u 1 \"src/assets/**/*\" dist/",
    "copy-views": "copyfiles -a -u 2 \"src/views/**/*.html\" dist/",
    "css": "npm-run-all --parallel css-compile* --sequential css-prefix css-minify*",
    "css-compile": "sass --style expanded --source-map --embed-sources --no-error-css --load-path=node_modules/ src/scss/:dist/css/",
    "css-lint": "npm-run-all --continue-on-error --parallel css-lint-*",
    "css-lint-stylelint": "stylelint \"**/*.{css,scss}\" --cache --cache-location .cache/.stylelintcache --rd",
    "css-minify": "cleancss -O1 --format breakWith=lf --with-rebase --source-map --source-map-inline-sources --output dist/css/ --batch --batch-suffix \".min\" \"dist/css/*.css\" \"!dist/css/*.min.css\" \"!dist/css/*rtl*.css\"",
    "css-prefix": "postcss --config build/postcss.config.js --replace \"dist/css/*.css\" \"!dist/css/*.min.css\"",
    "js": "npm-run-all --parallel js-compile* ",
    "js-compile": "cross-env PLUGINS=true babel src/js/ --out-dir dist/js/ --source-maps",
    "js-lint": "eslint --cache --cache-location .cache/.eslintcache --report-unused-disable-directives .",
    "localhost": "browser-sync start --server \"./dist\" --serveStatic \"./\" --files \"./dist/\"",
    "prettier": "prettier --print-width=160 --write \"dist\"",
    "pug": "npm-run-all --parallel pug-*",
    "pug-dist": "node build/pug.js --dest dist/",
    "pug-views": "node build/pug.js --dest src/views/",
    "release-version": "node build/change-version.js",
    "serve": "serve dist",
    "start": "npm-run-all --sequential clean css js copy --parallel localhost watch",
    "start-html": "npm-run-all --sequential clean css js copy --parallel localhost watch-assets watch-css watch-html watch-js",
    "start-pug": "npm-run-all --sequential clean css js copy --parallel localhost watch-assets watch-css watch-pug watch-js",
    "sync-assets": "syncdir src/assets dist/assets",
    "watch": "npm-run-all --parallel watch-*",
    "watch-assets": "nodemon --watch src/assets --exec \"npm run sync-assets\"",
    "watch-css": "nodemon --watch scss/ --ext scss --exec \"npm-run-all css-lint css-compile css-prefix\"",
    "watch-html": "nodemon --watch src/views --ext html --exec \"npm run copy-views\"",
    "watch-js": "nodemon --watch src/js --ext js --exec \"npm-run-all js-lint js-compile\"",
    "watch-pug": "nodemon --watch src/pug --ext pug --exec \"npm run pug-dist\"",
    "zip": "git archive -o coreui-pro-bootstrap-admin-template-v$npm_package_version.zip -9 HEAD"
  },
  "dependencies": {
    "@coreui/chartjs": "^3.0.0",
    "@coreui/coreui-pro": "^4.1.1",
    "@coreui/icons": "^2.1.0",
    "@coreui/utils": "^1.3.1",
    "chart.js": "^3.7.1",
    "datatables.net": "^1.11.5",
    "datatables.net-bs4": "^1.11.5",
    "fullcalendar": "^5.10.2",
    "jquery": "^3.6.0",
    "simplebar": "^5.3.6"
  },
  "devDependencies": {
    "@babel/cli": "^7.17.6",
    "@babel/core": "^7.17.5",
    "@babel/preset-env": "^7.16.11",
    "@coreui/vendors-injector": "^1.1.4",
    "autoprefixer": "^10.4.2",
    "browser-sync": "^2.27.7",
    "clean-css-cli": "^5.5.2",
    "copyfiles": "^2.4.1",
    "cross-env": "^7.0.3",
    "eslint": "^8.10.0",
    "eslint-config-xo": "^0.40.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-unicorn": "^41.0.0",
    "find-unused-sass-variables": "^4.0.3",
    "foreach-cli": "^1.8.1",
    "globby": "^11.1.0",
    "minimist": "^1.2.5",
    "mkdirp": "^1.0.4",
    "nodemon": "^2.0.15",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.7",
    "postcss-cli": "^9.1.0",
    "postcss-combine-duplicated-selectors": "^10.0.3",
    "prettier": "2.5.1",
    "pug": "^3.0.2",
    "rimraf": "^3.0.2",
    "sass": "1.49.9",
    "serve": "^13.0.2",
    "shelljs": "^0.8.5",
    "stylelint": "^14.5.3",
    "stylelint-config-twbs-bootstrap": "^3.0.1",
    "sync-directory": "^4.0.12"
  }
}

```

**Comment by mrholek** [comment]
@abunch please download one more time version 4.1.1,  there was a wrong file.

**Comment by abunch** [comment]
@mrholek that took care of it.  Thanks!

<img width="261" alt="Screen Shot 2022-03-21 at 7 22 09 PM" src="https://user-images.githubusercontent.com/2077840/159383834-c6444df2-084d-4dfd-bd3a-d7a30f9202db.png">
